Fix for deprecation error.
The AMI build is failing due to a deprecated function called in older actions.

eg. https://github.com/sailthru/packer/actions/runs/4526438768/jobs/7971610229

```
Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
Error: Build status: FAILED
```

Solution:
Update the relevant packages as was done in the upstream repo:
https://github.com/aws-actions/aws-codebuild-run-build/blob/bb79642b65f722f93f803dcede4fadd8dd85d0b6/package.json